events {}
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  server {
    listen 80;
    root /usr/share/nginx/html;
    # fallback
    location / {
      try_files $uri /index.html;
    }
    # Proxy API to FastAPI
    location /app/ {
      proxy_pass http://app:8000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_http_version 1.1;
    }
  }
}
