name: Run Tests (pytest)
on:
    push:
        branches: ["master"]
        paths:
            - "app/**"
            - "tests/**"
            - "pyproject.toml"
    pull_request:
        branches: ["master"]
        paths:
            - "app/**"
            - "tests/**"
            - "pyproject.toml"

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version-file: .python-version
            - name: Set up uv
              uses: astral-sh/setup-uv@v6

            - name: Install dependencies
              run: uv sync

            - name: Run tests with coverage
              run: |
                  uv run pytest --cov=app tests/
